const {test}=require('node:test'),assert=require('node:assert/strict'),{prefix,rrf,retrievalMetrics,run}=require('./engine');const last=f=>f.at(-1);
test('Common prefix handles append, middle changes, first changes',()=>{assert.equal(prefix(['a','b'],['a','b','c']),2);assert.equal(prefix(['a','b','c'],['a','x','c']),1);assert.equal(prefix([],['a']),0);assert.equal(last(run('cache','middle')).payload.commonPrefix,3);assert.equal(last(run('cache','start')).payload.commonPrefix,0);});
test('RRF exact scores and duplicate list rejection',()=>{const r=rrf([['A','B'],['B','C']],3);assert.equal(r[0].id,'B');assert.ok(Math.abs(r[0].score-(1/5+1/4))<1e-12);assert.throws(()=>rrf([['A','A']]));});
test('Binary retrieval metrics correct and bounded',()=>{const m=retrievalMetrics(['A','B','C'],['B','C'],3);assert.equal(m.recall,1);assert.equal(m.rr,.5);assert.ok(m.ndcg>0&&m.ndcg<=1);assert.deepEqual(retrievalMetrics(['A'],[],3),{recall:0,rr:0,ndcg:0});assert.throws(()=>retrievalMetrics(['A','A'],['A'],3));});
test('Tool results pair with all calls, invalid call errors then repairs',()=>{const f=run('loop','invalid'),messages=last(f).payload.messages;const calls=messages.flatMap(m=>m.tool_calls||[]),results=messages.filter(m=>m.role==='tool');assert.deepEqual(calls.map(c=>c.id),results.map(r=>r.tool_call_id));assert.equal(calls[0].arguments.a,'twelve');assert.equal(calls[1].arguments.a,12);assert.ok(results[0].content.startsWith('error'));assert.equal(f[0].payload.messages.length,1);});
test('Refund and malicious skill never execute external action',()=>{assert.equal(last(run('foundations','blocked')).payload.executed,false);assert.equal(last(run('skills','malicious')).payload.executed,false);});
test('State enforces retry limit and preserves verified status',()=>{const f=last(run('state','summary',3));assert.equal(f.payload.attempts,3);assert.equal(f.payload.stopped,true);assert.equal(f.payload.summary.verified,false);assert.throws(()=>run('state','summary',0));});
test('Memory update has consent alternative, tenants and multiagent conflicts',()=>{assert.equal(last(run('memory','update')).payload.profile.language,'en');assert.equal(last(run('memory','temporary')).payload.profile,null);assert.equal(last(run('knowledge','graph')).payload.allowed,false);assert.equal(last(run('multiagent','conflict')).payload.needsReview,true);});
test('All 12 units produce independent deterministic traces',()=>{const pairs=[['foundations','valid'],['loop','normal'],['cache','append'],['skills','safe'],['state','isolate'],['memory','update'],['rag','contextual'],['hybrid','rerank'],['knowledge','tree'],['evaluation','harness'],['multimodal','native'],['multiagent','normal']];for(const [id,mode]of pairs){const a=run(id,mode),b=run(id,mode);assert.deepEqual(a,b);assert.ok(a.length>=3);assert.ok(a.every(f=>f.message&&f.nodes.length));a[0].nodes[0].label='changed';assert.notEqual(b[0].nodes[0].label,'changed');}});
