/* No dependencies or remote scripts. */
(()=>{'use strict';const $=id=>document.getElementById(id),lessons=window.DSLessons;let lesson,frames=[],index=0,timer=null,completed=new Set();try{const saved=JSON.parse(localStorage.getItem('ds-lab-progress')||'[]');if(Array.isArray(saved))completed=new Set(saved.filter(x=>lessons.some(l=>l.id===x)));}catch{}
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function pause(){clearInterval(timer);timer=null;$('play').textContent='自动播放';}
function navigation(){const nav=$('topics');nav.replaceChildren();for(const [i,l]of lessons.entries()){const b=el('button',`${String(i+1).padStart(2,'0')}  ${l.title}`,l===lesson?'active':'');b.setAttribute('aria-current',l===lesson?'page':'false');if(completed.has(l.id))b.append(el('small','✓'));b.onclick=()=>{location.hash=l.id;};nav.append(b);}$('progress').textContent=`已学习 ${completed.size} / ${lessons.length} 章`;$('complete').textContent=completed.has(lesson?.id)?'已学 ✓（点击取消）':'标记本章已学';}
function select(){pause();lesson=lessons.find(l=>l.id===location.hash.slice(1))||lessons[0];$('title').textContent=lesson.title;$('category').textContent=lesson.tag;$('summary').textContent=lesson.summary;$('complexity').textContent=lesson.complexity;$('operation').replaceChildren(...lesson.ops.map(([v,t])=>{const n=el('option',t);n.value=v;return n;}));$('values').disabled=lesson.id==='graph';$('values').value=lesson.id==='hash'?'7,14,3,10,5':lesson.id==='tree'?'7,3,9,1,5,8,11':'7,3,9,1,5';$('target').value=lesson.id==='graph'?0:5;$('cards').replaceChildren(...lesson.cards.map(([h,t])=>{const n=el('article');n.append(el('h4',h),el('p',t));return n;}));const [q,answers,right,explain]=lesson.quiz;$('question').textContent=q;$('feedback').textContent='';$('answers').replaceChildren(...answers.map((t,i)=>{const b=el('button',t);b.onclick=()=>{for(const btn of $('answers').children)btn.className='';b.className=i===right?'correct':'wrong';$('feedback').textContent=(i===right?'正确。':'再想想。')+explain;};return b;}));navigation();generate();}
function generate(){pause();try{const raw=$('target').value;if(!/^[-+]?\d+$/.test(raw))throw Error('目标值不能为空，且必须是整数。');frames=DSEngine.trace(lesson.id,DSEngine.parse($('values').value),$('operation').value,Number(raw));index=0;$('error').textContent='';render();}catch(e){$('error').textContent=e.message;}}
function cell(value,i,f){const n=el('div',value===null?'·':String(value),'cell'+(f.hot.includes(i)?' hot':'')+(f.done.includes(i)?' done':''));if(f.range&&(i<f.range[0]||i>f.range[1]))n.classList.add('dim');n.append(el('small',String(i)));return n;}
function svgElement(tag,attrs){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;}
function drawGraph(f){const svg=svgElement('svg',{viewBox:'0 0 650 260',class:'tree',role:'img','aria-label':lesson.title+'当前结点状态'});let nodes=f.nodes||f.values.map(value=>({value})),positions=[];if(f.nodes){let order=[];const walk=(i,d)=>{if(i===null)return;walk(nodes[i].left,d+1);order.push([i,d]);walk(nodes[i].right,d+1);};if(nodes.length)walk(0,0);const maxDepth=Math.max(0,...order.map(x=>x[1]));order.forEach(([i,d],rank)=>positions[i]=[35+(rank+.5)*580/Math.max(1,nodes.length),30+d*190/Math.max(1,maxDepth)]);}else if(lesson.id==='graph'){positions=[[70,120],[210,45],[210,200],[370,100],[425,220],[570,165]];}else nodes.forEach((_,i)=>{let d=Math.floor(Math.log2(i+1)),offset=i-(2**d-1);positions.push([(offset+.5)*650/(2**d),32+d*65]);});
const edges=f.edges||nodes.flatMap((n,i)=>f.nodes?[n.left,n.right].filter(x=>x!==null).map(j=>[i,j]):[2*i+1,2*i+2].filter(j=>j<nodes.length).map(j=>[i,j]));for(const [u,v]of edges){if(!positions[u]||!positions[v])continue;const [x1,y1]=positions[u],[x2,y2]=positions[v];svg.append(svgElement('line',{x1,y1,x2,y2}));}nodes.forEach((n,i)=>{const [cx,cy]=positions[i];const g=svgElement('g',{class:f.hot.includes(i)?'hot':f.done.includes(i)?'done':''});g.append(svgElement('circle',{cx,cy,r:18}));const t=svgElement('text',{x:cx,y:cy});t.textContent=n.value;g.append(t);svg.append(g);});$('visual').append(svg);}
function render(){const f=frames[index];if(!f)return;$('visual').replaceChildren();if(['tree','graph','heap'].includes(lesson.id))drawGraph(f);else if(lesson.id==='hash'&&f.buckets){const container=el('div');f.buckets.forEach((b,i)=>{const row=el('div',undefined,'hash-row');row.style.cssText='display:flex;align-items:center;gap:10px;margin:8px 0';row.append(el('span',`桶 ${i}`));for(const v of b)row.append(cell(v,i,{hot:i===f.bucket?[i]:[],done:[]}));if(!b.length)row.append(el('span','∅','empty'));container.append(row);});$('visual').append(container);}else{const container=el('div',undefined,lesson.id==='stack'?'vertical':lesson.id==='sort'?'bars':'');if(!container.className)container.style.cssText='display:flex;gap:8px;flex-wrap:wrap;align-items:center;justify-content:center';f.values.forEach((v,i)=>{const n=cell(v,i,f);if(lesson.id==='sort')n.style.setProperty('--height',`${35+(Number(v)+99)/198*125}px`);container.append(n);if(lesson.id==='list'&&i<f.values.length-1)container.append(el('span','→','arrow'));});if(lesson.id==='list')container.append(el('span','→ null','empty'));if(!f.values.length)container.append(el('span','空结构','empty'));$('visual').append(container);}
$('step').textContent=`STEP ${index+1} / ${frames.length}`;$('message').textContent=f.message;$('state').textContent=f.frontier?'等待队列：['+f.frontier.join(', ')+']':f.nodes?'结点数：'+f.nodes.length:f.buckets?'桶数：7':`当前数据：[${f.values.map(x=>x===null?'空位':x).join(', ')}]`+(f.held!==undefined?` · 暂存：${f.held}`:'');$('back').disabled=index===0;$('next').disabled=index===frames.length-1;$('scrub').max=frames.length-1;$('scrub').value=index;}
$('settings').onsubmit=e=>{e.preventDefault();generate();};$('back').onclick=()=>{pause();if(index>0)index--;render();};$('next').onclick=()=>{pause();if(index<frames.length-1)index++;render();};$('reset').onclick=()=>{pause();index=0;render();};$('scrub').oninput=()=>{pause();index=Number($('scrub').value);render();};$('play').onclick=()=>{if(timer){pause();return;}if(index===frames.length-1)index=0;render();$('play').textContent='暂停';timer=setInterval(()=>{if(index<frames.length-1){index++;render();}if(index===frames.length-1)pause();},Number($('speed').value));};$('speed').onchange=pause;
function save(){try{localStorage.setItem('ds-lab-progress',JSON.stringify([...completed]));}catch{}navigation();}$('complete').onclick=()=>{if(completed.has(lesson.id))completed.delete(lesson.id);else completed.add(lesson.id);save();};$('clear-progress').onclick=()=>{if(confirm('清除本浏览器的数据结构学习记录？')){completed.clear();save();}};window.addEventListener('hashchange',select);window.addEventListener('pagehide',pause);select();})();
